springboot:
  jwt:
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting #JWT를 만들때 사용하는 키 , 길이가 짧으면 에러 남 #자바코드로 사용하고 싶을경우를 위해, 관리하기 편해서 작성함
    header-scheme-name: authorization
    token-type: Bearer
    access token-expiry: 7200000 #2시간 상수처럼 값을 가져다 사용
    refresh-token-expiry: 1296000000 #15일

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greengram3
    username: root
    password: green502

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

fcm:
  certification: serviceAccountKey.json